# Generated by Django 5.0.3 on 2024-03-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileSuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial", models.CharField()),
                ("pilot", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=100)),
            ],
        ),
    ]
